name: Sync WSL repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-prod:
    runs-on: self-hosted

    steps:
      - name: Sync repo in WSL
        run: |
          cd /home/sjiqidze/actions-runner
          git fetch origin
          git checkout main
          git reset --hard origin/main
          git clean -fd
          echo "WSL sync completed ✅"